# Production Docker Compose for AWS deployment
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - APP_JWT_SECRET=${JWT_SECRET}
      - APP_CORS_ALLOWED_ORIGINS=${FRONTEND_URL}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/ecs/storypublisher-backend
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=${BACKEND_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/ecs/storypublisher-frontend
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs
